### ISSUE TITLE
fix version mismatch in Elrond explorer using official docker image

### ISSUE THREAD

**Issue by vitalyevodin** [ElrondNetwork/elrond-config-mainnet#117]
Using official docker image for elrond-node in mainnet/testnet/devnet shows version mismatch in elrond.explorer even if version is match
all needed is change this line in docker/Dockerfile
`RUN go build -i -v -ldflags="-X main.appVersion=$(git --git-dir /config/.git describe --tags --long --dirty)"`

**Comment by vitalyevodin** [comment]
Pull request
https://github.com/ElrondNetwork/elrond-config-mainnet/pull/118

**Comment by bogdan-rosianu** [comment]
Thank you for your contribution! Indeed, there was an issue and your PR fixed it. We have merged it! :pray:
