### ISSUE TITLE
Nodes stop on block, shard 1

### ISSUE THREAD

**Issue by bo-everstake** [ElrondNetwork/elrond-config-mainnet#139]
Main node validator stop on block everstake-1-05 and backup node everstake-4-02 (same trouble). Try restart - its not help resolve trouble. Logs in attach. 
[everstake-4-02.zip](https://github.com/ElrondNetwork/elrond-config-mainnet/files/9153812/everstake-4-02.zip)
[everstake-1-05.zip](https://github.com/ElrondNetwork/elrond-config-mainnet/files/9153816/everstake-1-05.zip)

**Comment by iulianpascalau** [comment]
We are unable to track the problem because the log level is set to `INFO`. Please upload here logs with the log level set to `DEBUG`. Thanks

**Comment by bo-everstake** [comment]
[everstake-4-02.zip](https://github.com/ElrondNetwork/elrond-config-mainnet/files/9156702/everstake-4-02.zip)
[everstake-1-05.zip](https://github.com/ElrondNetwork/elrond-config-mainnet/files/9156703/everstake-1-05.zip)
Add debug logs.

**Comment by iulianpascalau** [comment]
These are also logged with `INFO` log level. Are you using custom scripts for your nodes?

**Comment by bo-everstake** [comment]
Sorry, but now i clean db and resync both nodes.

**Comment by bo-everstake** [comment]
I am using elrond-go-scripts - standart , end setting up log lvl in node unit.

**Comment by iulianpascalau** [comment]
`DEBUG` log level helps us in such cases. Otherwise we are unable to track the possible problem. Please reopen issue in elrond-go repo if you have a new batch of logs with the `DEBUG` level. Thanks.
